### ISSUE TITLE
Noise sources used for the docs

### ISSUE THREAD

**Issue by theogf** [mfiano/CoherentNoise.jl#11] opened 2022-09-10 12:20 UTC
Hey, first thanks for this package. The content is awesome and the docs are super nice!
I would like to use some of the examples you show in your table, but it's hard to know which exact combination was used (as code).
It would be great to have this in the table displayed here (https://mfiano.github.io/CoherentNoise.jl/dev/algorithms/).

**Comment by mfiano** [comment] 2022-09-10 17:07
Hello @theogf, and thank you!

Were you interested in the line or surface plots, or the noise parameters used for them?

Unfortunately, some correctness changes made to the code recently invalidated those example images, so likely none of them are going to be exactly reproducible. I have to come up with a process to automatically generate them, which shouldn't be too hard, but it took me about a week to manually create all of them, mostly because of the video captures.

I would like to help you generate the noise you are looking for, so more information would be helpful.

**Comment by theogf** [comment] 2022-09-10 17:08
Haha I am kindof interested in most of them to be honest 😂.
For generating code this kind of docs automatically, I would highly recommend looking at Literate.jl!

**Comment by mfiano** [comment] 2022-09-10 17:35
I will do that. All of the examples in the algorithms section were generated with the raw noise functions, with their default arguments unless otherwise noted (like the smooth versions of the simplex variants). They should be easy to reproduce at least similarly. If you need more help though, I'm always free!

**Comment by mfiano** [comment] 2022-09-10 17:36
Closing this issue for now, as the discussion migrated to another forum, but feel free to re-open it if there is anything more to add!

**Closed by mfiano** 2022-09-10 17:36 UTC
